[package]
authors = ["CoBloX developers <team@coblox.tech>"]
edition = "2018"
name = "comit_i"
version = "0.1.0"

[lib]
# Cannot run doctest with rust-embed as the path to the folder in the derive macro is relative to the root
# whereas doctest is run from inside the crate making the path invalid
doctest = false

[dependencies]
rust-embed = "5.1"

[build-dependencies]
reqwest = { version = "0.9", default-features = false, features = ["default-tls-vendored"] }
tempfile = "3"
unzip = "0.1"
